### ISSUE TITLE
About KataGo Aggressive

### ISSUE THREAD

**Issue by hope366** [wonsiks/BadukMegapack#19]
Hello.
In the previous megapack, the Handicap entry in katago's gtp.cfg was
"dynamicPlayoutDoublingAdvantageCapPerOppLead = 0.045
"playoutDoublingAdvantagePla = WHITE
only had been enabled.
In the latest katago-v1.4.2 default_gtp.cfg, all items in Handicap are commented out.
So I think that wonsics created "aggressive_gtp.cfg" for sabaki's "KataGo(~b) Aggressive".
In "KataGo(~b) Aggressive,
playoutDoublingAdvantage=1.0" and "playoutDoublingAdvantagePla=WHITE" are in effect and "dynamicPlayoutDoublingAdvantageCapPerOppLead = 0.045" is not applied.

Please tell me what you meant by setting "playoutDoublingAdvantage" to "1" and why you ruled out "dynamicPlayoutDoublingAdvantageCapPerOppLead = 0.045".

**Comment by wonsiks** [comment]
I'm not sure if this is always right but in aggressive setting I've made playoutDoublingAdvantage value static (1.0) instead of making it dynamically change with opponent's leading.
As the static playoutDoublingAdvantage value, KataGo's aggressiveness will varyied.
User can change the value between -3.0 and 3.0 range as I know.
Which value is better? I don't know. Just need to give it a try.

**Comment by hope366** [comment]
By dynamic, you mean that the bigger the opponent's lead, the more aggressive they become!
I didn't fully understand it from the description of the CFG file alone, but I feel like I understood it from wonsics' answer.
Thank you very much.

**Comment by hope366** [comment]
Thank you wonsiks for your kind response. Thank you very much.
Close here.
